<h4> Function to get a list of random values between an interval </h4>

In [12]:
from random import randint

def randomValues (begin, end, length, allowedToRepeat = False):
    if end < begin: 
        return []
    
    values = []
    if allowedToRepeat:
        while (len(values) < length):
            values.append(randint(begin,end))
    else:
        if (end-begin+1) >= length:
            while (len(values) < length):
                i = randint(begin, end)
                while i in values:
                    i = randint(begin,end)
                values.append(i)
    
    return values

<h4> Functions to stem and remove stop words. </h4>

In [13]:
from nltk.stem.porter import PorterStemmer

def stemSentence(sentence):
    
    if not sentence: 
        return sentence
    
    stemmer = PorterStemmer(mode=PorterStemmer.ORIGINAL_ALGORITHM)
    stemmedWords = list(map(stemmer.stem, sentence.split(' ')))
    stemmedSentence = stemmedWords[0]
    
    for i in range(1, len(stemmedWords)):
        stemmedSentence += ' ' + stemmedWords[i]
        
    return stemmedSentence

def removeStopwordsFromSentence(sentence, stopwords = []):
    
    if not sentence or not stopwords:
        return sentence
    
    sentence = sentence.lower()
    
    newString = ''
    for c in sentence:
        newString += c if c.isalnum() else ' '
    sentence = newString
    
    words = sentence.split(' ')
    clearSentence = ''
    
    for i in range(0, len(words)):
        
        word = words[i]
        if clearSentence and clearSentence[-1] != ' ':
            clearSentence += ' '
        clearSentence += word if word not in stopwords else ''
        
    return clearSentence

<h4> Opening general log file </h4>

In [14]:
generalLogFile = open('general_log_file.txt', 'w')
generalLogFile.write('GENERAL LOG FILE\n\n')

18

<h4> Reading music lyrics files </h4>

In [15]:
from pathlib import Path
import collections, numpy, operator
from operator import itemgetter

p = Path('./')
allMusicFiles = list(p.glob('**/*.txt'))
print('Total of music files: ', len(allMusicFiles))

generalLogFile.write('Total of music files: '+str(len(allMusicFiles))+'\n\n')

p = Path('./2 - English')
allMusicLyrics = []
allMusicFiles = list(p.glob('**/*.txt'))

print('Total of music files in English: ',len(allMusicFiles))

generalLogFile.write('Total of music files in English: '+str(len(allMusicFiles))+'\n\n')

sampleSize = 3000
# sampleSize = -1

generalLogFile.write('Sample size: '+str(sampleSize)+'\n\n')

if sampleSize != -1:
    randomIndexes = randomValues(0,len(allMusicFiles)-1,sampleSize)
    allMusicFiles = itemgetter(*randomIndexes)(allMusicFiles)
    sampleSize = len(allMusicFiles)

print('Amount of music files: ', len(allMusicFiles))

for file in allMusicFiles:
    with file.open() as f:
        allMusicLyrics.append(f.read().replace('\n', ' '))
        f.close()
        
print('Amount of lyrics: ', len(allMusicLyrics))

Total of music files:  52673
Total of music files in English:  25693
Amount of music files:  3000
Amount of lyrics:  3000


<h4> Reading stop words dictionary file. </h4> 

In [16]:
dictionaryFile = open('NewDictionary.txt','r')
dictionaryContent = dictionaryFile.read()
dictionaryFile.close()
dictionaryList = []
for word in dictionaryContent.split(','):
    if '"' in word:
        dictionaryList.append(word.replace('"',''))
    else:
        dictionaryList.append(word.replace('\'',''))

generalLogFile.write('Amount of dictionary words: '+str(len(dictionaryList))+'\n\n')

print('Amount of dictionary words: ', len(dictionaryList))
print(dictionaryList)

Amount of dictionary words:  2696
['a', 'about', 'above', 'across', 'after', 'again', 'against', 'all', 'almost', 'alone', 'along', 'already', 'also', 'although', 'always', 'am', 'among', 'an', 'and', 'another', 'any', 'anybody', 'anyone', 'anything', 'anywhere', 'are', 'area', 'areas', "aren't", 'around', 'as', 'ask', 'asked', 'asking', 'asks', 'at', 'away', 'b', 'back', 'backed', 'backing', 'backs', 'be', 'became', 'because', 'become', 'becomes', 'been', 'before', 'began', 'behind', 'being', 'beings', 'below', 'best', 'better', 'between', 'big', 'both', 'but', 'by', 'c', 'came', 'can', 'cannot', "can't", 'case', 'cases', 'certain', 'certainly', 'clear', 'clearly', 'come', 'could', "couldn't", 'd', 'did', "didn't", 'differ', 'different', 'differently', 'do', 'does', "doesn't", 'doing', 'done', "don't", 'down', 'downed', 'downing', 'downs', 'during', 'e', 'each', 'early', 'either', 'end', 'ended', 'ending', 'ends', 'enough', 'even', 'evenly', 'ever', 'every', 'everybody', 'everyone', '

<h4> Removing stop words and stemming music files. </h4>

In [17]:
totalOfWords = 0
totalOfRemovedWords = 0
clearedMusics = []

for music in allMusicLyrics:
    
    # Getting and acumulating amount of words in original music file
    
    amountOfWords = len(music.split(' '))
    totalOfWords += amountOfWords
    
    # Removing stop words and stemming music lyrics
    
    clearMusic = removeStopwordsFromSentence(music, dictionaryList)
    stemmedMusic = stemSentence(clearMusic)
    
    # Getting and acumulating amount of reduced words 
    
    newAmountOfWords = len(stemmedMusic.split(' '))
    reducedWords = amountOfWords - newAmountOfWords
    totalOfRemovedWords += reducedWords
    
    # Storing the new cleared music file 
    
    clearedMusics.append(stemmedMusic)
    
generalLogFile.write('Amount of words in original music files: '+str(totalOfWords)+'\n\n')
generalLogFile.write('Amount of removed words: '+str(totalOfRemovedWords)+'\n\n')

print('Amount of words in original music files: ', totalOfWords)
print('Amount of removed words: ', totalOfRemovedWords)

Amount of words in original music files:  772639
Amount of removed words:  471950


<h4> Bag of Words </h4> 

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
bagOfWordsResult = vectorizer.fit_transform(clearedMusics)

print(vectorizer.get_feature_names())
print(vectorizer.vocabulary_)

['aa', 'aah', 'aahh', 'aahndweni', 'aai', 'aand', 'aankhiya', 'aankhiyaan', 'aankhiyo', 'aarer', 'aaron', 'aay', 'ab', 'abab', 'abaelard', 'abandon', 'abandond', 'abat', 'abattoir', 'abbassarsi', 'abber', 'abbras', 'abc', 'abdimum', 'abdomen', 'abduct', 'abductor', 'abel', 'abençoada', 'abençoado', 'aber', 'abercrobi', 'abercrombi', 'aberdeen', 'aberr', 'abertura', 'abhorr', 'abi', 'abid', 'abil', 'abit', 'abject', 'abl', 'ablaz', 'abneg', 'abnorm', 'aboard', 'abomin', 'aborigin', 'abort', 'abou', 'abound', 'abraham', 'abrindo', 'abroad', 'abrupt', 'abruptli', 'absalom', 'absenc', 'absent', 'absichtlich', 'absolut', 'absolyutno', 'absorb', 'abstain', 'abstract', 'abstrair', 'absurd', 'abund', 'abus', 'abysm', 'abyss', 'abyssinia', 'ac', 'acabar', 'academi', 'acapella', 'acat', 'accecpt', 'acceler', 'accent', 'accept', 'access', 'accheiv', 'accid', 'accident', 'accidentist', 'acclaim', 'accolad', 'accomod', 'accompli', 'accomplish', 'accord', 'accordingli', 'account', 'accro', 'accross'

<h4> TF-IDF </h4>

In [19]:
from sklearn.feature_extraction.text import *

transformer = TfidfTransformer()

tfidf = transformer.fit_transform(bagOfWordsResult)
normalizedResult = tfidf.toarray()

print(transformer.idf_) ### Feature weitghts
print(tfidf.toarray()) ### Normalized values

[7.39726293 7.62040648 8.31355366 ... 8.31355366 8.31355366 8.31355366]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [20]:
def keyWordsOfEachGroup(musics, groups, amountOfGroups, amountOfKeyWords = 30):
    
    musicsOfEachGroup = []
    keyWrodsOfEachGroup = []
    for i in range(0, amountOfGroups):
        musicsOfEachGroup.append('')
        
    for i in range(0, len(groups)):
        group = groups[i]
        musicsOfEachGroup[group] += ' ' + musics[i]
        
    for moeg in musicsOfEachGroup:
        
        allWords = sorted(moeg.split(' '))
        filtered = filter(lambda a: a != '', allWords)
        counter = collections.Counter(filtered)
        counter = sorted(counter.items(), key=operator.itemgetter(1))
        amountOfWords = amountOfKeyWords if len(allWords) >= amountOfKeyWords else len(allWords)
        mostFrequentWords = []
        lessFrequentWords = []
        j = len(counter)-1
        for i in range(0, amountOfWords):
            if i >= len(counter):
                break
            mostFrequentWords.append(counter[j])
            lessFrequentWords.append(counter[i])
            j-=1
        keyWrodsOfEachGroup.append([mostFrequentWords, lessFrequentWords])
        
    return keyWrodsOfEachGroup

<h4> Agrupamento KMeans </h4> 

In [21]:
from sklearn.cluster import KMeans
import collections, numpy, operator
from operator import itemgetter
    
centroids = [2, 4, 8, 16] #[2, 4, 8, 16]

for c in centroids:
    
    kmeans = KMeans(n_clusters = c).fit(normalizedResult)
    results = kmeans.labels_
    
    print(results)

#     OPENING LOG FILE

    groupResultFile = open('kmeans_result_'+str(c)+'_centroids.txt', 'w')
    groupResultFile.write('KMeans result with '+str(c)+' centroids.\n\n')

#     DECLARING HELP VARIABLES

    amountOfMusicsOfEachGroup = collections.Counter(results)

    lastEnd = -1
    for k, v in sorted(amountOfMusicsOfEachGroup.items()):

        # SAVING AMOUNT OF REGISTER OF EACH GROUP IN LOG FILE

        groupResultFile.write('Grupo '+str(k+1)+': '+str(v)+' registros.\n')
        start = -1
        end = -1
        if k > 0:
            start = lastEnd
            end = lastEnd + v - 1
            lastEnd = lastEnd + v
        else:
            start = 0 
            end = v-1 
            lastEnd = v
            
    groupResultFile.write('\nKEY WORDS \n')
            
    amountOfKeyWords = 30
    groupsKeyWords = keyWordsOfEachGroup(clearedMusics, results, c, amountOfKeyWords)
    
    for i in range(0,len(groupsKeyWords)):
        
        keyWords = groupsKeyWords[i]
    
        groupResultFile.write('\n  Group '+str(i)+' \n')
    
        groupResultFile.write('\n    '+str(amountOfKeyWords)+' most frequent words: ')
        
        print('      ')

        for w, f in keyWords[0]:
            groupResultFile.write(str(w)+' ('+str(f)+'); ')

        groupResultFile.write('\n\n    '+str(amountOfKeyWords)+' less frequent words: ')
        
        print('      ')

        for w, f in keyWords[1]:
            groupResultFile.write(str(w)+' ('+str(f)+'); ')
            
        groupResultFile.write('\n')
        
#     STORING THE NAME OF EACH FILE IN AN ARRAY TO BE MANIPULATED LATER

#     The name pattern for each music file is: g - entire_document_name 
#     where g = the group of the file and 
#     entire_document_name = is the intire path plus the name of music file

    musicNames = [''] * sampleSize
    for i in range(0, sampleSize):
        musicNames[i] = str(results[i])+' - '+str(allMusicFiles[i])+'\n\n'
    musicNames.sort()
    
    analizedMusicNamesOfEachGroup = []
    start = 0
    end = 0
    for g in range(0, c):

        # CHOOSING AND STORING n RANDOM MUSICS OF EACH GROUP TO BE ANALIZED MANUALLY
        amountOfAnalizedMusicsOfEachGroup = 5
        
        start = end
        end = start + amountOfMusicsOfEachGroup[g]

        randomIndexes = []
        if amountOfMusicsOfEachGroup[g] <= amountOfAnalizedMusicsOfEachGroup:
            randomIndexes = range(start, end)
        else:
            randomIndexes = randomValues(start, end-1, amountOfAnalizedMusicsOfEachGroup)
            
        print(randomIndexes)

        analizedMusicNamesOfEachGroup.append(itemgetter(*randomIndexes)(musicNames))

#     SAVING THE MOST AND THE LESS FREQUENT WORDS OF EACH GROUP

    groupResultFile.write('\nFiles to be analized for each group\n')
    for i in range(0, c):
        groupResultFile.write('\nGroup '+str(i+1)+': \n\n')
        for musicName in analizedMusicNamesOfEachGroup[i]:
            groupResultFile.write(musicName+'\n')

    groupResultFile.close()

[0 0 1 ... 0 0 0]
      
      
      
      
[1622, 987, 1123, 59, 1940]
[2712, 2695, 2694, 2760, 2574]
[1 3 1 ... 1 3 3]
      
      
      
      
      
      
      
      
[29, 30, 185, 186, 197]
[277, 483, 255, 888, 753]
[1096, 1164, 1256, 1291, 1123]
[2917, 2357, 2904, 2243, 2773]
[4 2 1 ... 4 2 2]
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
[9, 0, 13, 12, 15]
[230, 145, 174, 264, 276]
[888, 825, 1768, 990, 1634]
[1850, 1788, 1878, 1847, 1967]
[2298, 2438, 2597, 2261, 2137]
[2797, 2695, 2830, 2798, 2701]
[2849, 2844, 2855, 2858, 2878]
[2943, 2982, 2972, 2992, 2895]
[ 3  2  6 ...  2  2 11]
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
[123, 103, 72, 135, 30]
[187, 201, 241, 224, 169]
[286, 372, 277, 339, 488]
[734, 652, 600, 731, 727]
[

<h4> Closing general log file. </h4>

In [22]:
generalLogFile.close()